# Generated by Django 4.0.6 on 2022-08-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='token',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
