# Generated by Django 4.0.6 on 2022-08-14 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_usuario_token_google'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenGoogle',
        ),
    ]
