# Generated by Django 4.0.6 on 2022-08-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=254)),
                ('categoria', models.CharField(choices=[('1', 'Abecedario'), ('2', 'Colores'), ('3', 'Comidas'), ('4', 'Geografia'), ('5', 'Modales'), ('6', 'Numeros'), ('7', 'Personas'), ('8', 'Preguntas'), ('9', 'Verbos')], default='1', max_length=2)),
            ],
        ),
    ]
