# Generated by Django 4.0.6 on 2022-09-21 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aprendizaje', '0002_usuariosena'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='media')),
                ('sena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aprendizaje.sena')),
            ],
        ),
    ]
