# Generated by Django 4.0.6 on 2022-10-07 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aprendizaje', '0004_sena_permite_signa_alter_videosena_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sena',
            name='permite_signa',
        ),
    ]
