# Generated by Django 4.0.6 on 2022-10-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendizaje', '0005_remove_sena_permite_signa'),
    ]

    operations = [
        migrations.AddField(
            model_name='sena',
            name='permite_signa',
            field=models.BooleanField(default=False),
        ),
    ]
