# Generated by Django 4.1 on 2022-10-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendizaje', '0006_sena_permite_signa'),
    ]

    operations = [
        migrations.AddField(
            model_name='sena',
            name='posicion_array_ia',
            field=models.IntegerField(null=True),
        ),
    ]
