# Generated by Django 4.0.6 on 2022-11-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendizaje', '0007_sena_posicion_array_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='sena',
            name='orden',
            field=models.IntegerField(null=True),
        ),
    ]
